POST http://127.0.0.1:8000/api/login/
Content-Type: application/json

{"username": "rahmdel","password": "rahmdel"}


###

POST http://127.0.0.1:8000/api/singup/
Content-Type: application/json

{"username": "admin1","password": "admin","email": "admin@gmail.com"}


### 
GET http://127.0.0.1:8000/api/test_token
Content-Type: application/json
Authorization: Token 5f95ecb300b36e88107fafa48f915eb384261094
{}